spring:
  application:
    name: online-menu
  data:
    mongodb:
      uri: ${DB_URL}
#S3
aws:
  region: ${AWS_REGION}
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}
  s3:
    bucketname: online-delivery-bucket

#jwt
jwt:
  secret:
    key: ${JWT_SECRET}

